### ISSUE TITLE
Feed not updating

### ISSUE THREAD

**Issue by samwilson** [gravitystorm/blogs.osm.org#73]
Not sure if this is a transient error, but currently https://blogs.openstreetmap.org/atom.xml does not have any content:

```
$ curl -i https://blogs.openstreetmap.org/atom.xml
HTTP/2 200 
strict-transport-security: max-age=31536000; includeSubDomains; preload
last-modified: Thu, 23 Nov 2023 22:37:04 GMT
accept-ranges: bytes
content-length: 0
vary: Accept-Encoding
content-type: application/xml
date: Thu, 23 Nov 2023 22:57:16 GMT
server: Apache/2.4.54 (Ubuntu)
```

**Comment by samwilson** [comment]
It's been like this since before 2023-11-22 15:37:43 Z.

**Comment by tomhughes** [comment]
This is unlikely to be an issue with this repository as it hasn't changed for ages - it's probably better raised as an operational issue in https://github.com/openstreetmap/operations/issues/ initially and we can look into what is going on.

**Comment by tomhughes** [comment]
This isn't specific to atom.xml in any case - the feed in general is not updating.

**Comment by tomhughes** [comment]
Full backtrace of the error:

```
*** error: no implicit conversion of nil into String

bundler: failed to load command: pluto (/home/tom/.bundle/ruby/3.2.0/bin/pluto)
(erb):17:in `escapeHTML': no implicit conversion of nil into String (TypeError)
	from (erb):17:in `block in make_for'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-models-1.6.2/lib/pluto/models/utils.rb:38:in `block in each'
	from /home/tom/.bundle/ruby/3.2.0/gems/activerecord-6.1.7.6/lib/active_record/relation/delegation.rb:88:in `each'
	from /home/tom/.bundle/ruby/3.2.0/gems/activerecord-6.1.7.6/lib/active_record/relation/delegation.rb:88:in `each'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-models-1.6.2/lib/pluto/models/utils.rb:16:in `each'
	from (erb):13:in `make_for'
	from /usr/share/ruby/erb.rb:429:in `eval'
	from /usr/share/ruby/erb.rb:429:in `result'
	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/erb/template.rb:23:in `render'
	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/erb/templater.rb:45:in `block in merge_pak'
	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/manifest.rb:47:in `block in each'
	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/manifest.rb:47:in `each'
	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/manifest.rb:47:in `each'
	from /home/tom/.bundle/ruby/3.2.0/gems/pakman-1.1.0/lib/pakman/erb/templater.rb:25:in `merge_pak'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-merge-1.1.0/lib/pluto/merge/formatter.rb:79:in `make_for'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-merge-1.1.0/lib/pluto/merge/formatter.rb:35:in `run'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:290:in `block (3 levels) in <top (required)>'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:270:in `each'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:270:in `block (2 levels) in <top (required)>'
	from /home/tom/.bundle/ruby/3.2.0/gems/gli-2.21.1/lib/gli/command_support.rb:131:in `execute'
	from /home/tom/.bundle/ruby/3.2.0/gems/gli-2.21.1/lib/gli/app_support.rb:298:in `block in call_command'
	from /home/tom/.bundle/ruby/3.2.0/gems/gli-2.21.1/lib/gli/app_support.rb:311:in `call_command'
	from /home/tom/.bundle/ruby/3.2.0/gems/gli-2.21.1/lib/gli/app_support.rb:85:in `run'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto/cli/main.rb:390:in `<top (required)>'
	from /home/tom/.bundle/ruby/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
	from /home/tom/.bundle/ruby/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/tom/.bundle/ruby/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/tom/.bundle/ruby/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/lib/pluto.rb:24:in `main'
	from /home/tom/.bundle/ruby/3.2.0/gems/pluto-1.3.4/bin/pluto:5:in `<top (required)>'
	from /home/tom/.bundle/ruby/3.2.0/bin/pluto:25:in `load'
	from /home/tom/.bundle/ruby/3.2.0/bin/pluto:25:in `<top (required)>'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /home/tom/.bundle/ruby/3.2.0/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
```

**Comment by samwilson** [comment]
Thanks!

Reported at https://github.com/openstreetmap/operations/issues/1000
